title: Wallrunning technical breakdown
description: A quick overview on my take on the kinematic character controller and famous movement mechanic wall running
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
